// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyRecord.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoneyRecord.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MoneyRecordDbContext))]
    [Migration("20260825050834_LedgerAppendOnlyGuards")]
    partial class LedgerAppendOnlyGuards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("TxnNoSeq");

            modelBuilder.Entity("MoneyRecord.Domain.Entities.AdjustmentType", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("smallint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_AdjustmentTypes_Code");

                    b.ToTable("AdjustmentTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Code = "CashCorrection",
                            Name = "Cash Correction"
                        },
                        new
                        {
                            Id = (byte)2,
                            Code = "FloatTopUp",
                            Name = "Float Top-up"
                        },
                        new
                        {
                            Id = (byte)3,
                            Code = "FloatWithdrawal",
                            Name = "Float Withdrawal"
                        });
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSensitive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("UQ_AppSettings_Key");

                    b.ToTable("AppSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsSensitive = false,
                            Key = "shopName",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "????????? ?????",
                            ValueType = "string"
                        },
                        new
                        {
                            Id = 2,
                            IsSensitive = true,
                            Key = "dayBoundaryOffsetHours",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "0",
                            ValueType = "int"
                        },
                        new
                        {
                            Id = 3,
                            IsSensitive = false,
                            Key = "pendingExpiryMinutes",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "30",
                            ValueType = "int"
                        },
                        new
                        {
                            Id = 4,
                            IsSensitive = false,
                            Key = "duplicateWindowMinutes",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "5",
                            ValueType = "int"
                        },
                        new
                        {
                            Id = 5,
                            IsSensitive = false,
                            Key = "txnAmountCap",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "10000000",
                            ValueType = "int"
                        },
                        new
                        {
                            Id = 6,
                            IsSensitive = false,
                            Key = "lowBalanceCashThreshold",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "100000",
                            ValueType = "int"
                        },
                        new
                        {
                            Id = 7,
                            IsSensitive = false,
                            Key = "lowBalanceFloatThresholdPerAccount",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "50000",
                            ValueType = "int"
                        },
                        new
                        {
                            Id = 8,
                            IsSensitive = false,
                            Key = "receiptFooterText",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Value = "???????????????",
                            ValueType = "string"
                        });
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("character varying(40)");

                    b.Property<long?>("ActorUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("NewValuesJson")
                        .IsUnicode(true)
                        .HasColumnType("text");

                    b.Property<string>("OldValuesJson")
                        .IsUnicode(true)
                        .HasColumnType("text");

                    b.Property<long?>("ShopId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("IX_AuditLogs_ShopId_CreatedAt");

                    b.HasIndex("ActionCode", "CreatedAtUtc")
                        .HasDatabaseName("IX_AuditLogs_ActionCode_CreatedAt");

                    b.HasIndex("ActorUserId", "CreatedAtUtc")
                        .HasDatabaseName("IX_AuditLogs_Actor_CreatedAt");

                    b.HasIndex("EntityType", "EntityId", "CreatedAtUtc")
                        .HasDatabaseName("IX_AuditLogs_EntityType_EntityId_CreatedAt");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.CashAdjustment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte>("AdjustmentTypeId")
                        .HasColumnType("smallint");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<long?>("ApprovedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("BalanceAfter")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Direction")
                        .HasColumnType("smallint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("AdjustmentTypeId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("CashAdjustments", null, t =>
                        {
                            t.HasCheckConstraint("CK_CashAdj_Amount_Positive", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.CashLedgerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<long>("BalanceAfter")
                        .HasColumnType("bigint");

                    b.Property<long?>("CashAdjustmentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Direction")
                        .HasColumnType("smallint");

                    b.Property<byte>("SourceType")
                        .HasColumnType("smallint");

                    b.Property<long?>("TransactionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CashAdjustmentId")
                        .HasDatabaseName("IX_CashLedger_CashAdjustmentId")
                        .HasFilter("\"CashAdjustmentId\" IS NOT NULL");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_CashLedger_CreatedAt");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("IX_CashLedger_TransactionId")
                        .HasFilter("\"TransactionId\" IS NOT NULL");

                    b.ToTable("CashLedgerEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_CashLedger_Amount_Positive", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_CashLedger_Source_Xor", "(\"SourceType\" = 1 AND \"TransactionId\" IS NOT NULL AND \"CashAdjustmentId\" IS NULL) OR (\"SourceType\" = 2 AND \"CashAdjustmentId\" IS NOT NULL AND \"TransactionId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.CommissionEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("BatchRef")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("character varying(300)");

                    b.Property<byte>("SourceId")
                        .HasColumnType("smallint");

                    b.Property<long?>("TransactionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_CommissionEntries_CreatedAt");

                    b.HasIndex("SourceId");

                    b.HasIndex("TransactionId");

                    b.ToTable("CommissionEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_CommissionEntry_Amount_Positive", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_CommissionEntry_Source_Xor", "(\"TransactionId\" IS NOT NULL AND \"BatchRef\" IS NULL) OR (\"BatchRef\" IS NOT NULL AND \"TransactionId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.CommissionSource", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("smallint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_CommissionSources_Code");

                    b.ToTable("CommissionSources", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Code = "PerTxnAuto",
                            Name = "Per-Txn Auto"
                        },
                        new
                        {
                            Id = (byte)2,
                            Code = "PerTxnManual",
                            Name = "Per-Txn Manual"
                        },
                        new
                        {
                            Id = (byte)3,
                            Code = "PeriodicBatch",
                            Name = "Periodic Batch"
                        },
                        new
                        {
                            Id = (byte)4,
                            Code = "Adjustment",
                            Name = "Adjustment"
                        });
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long?>("ModifiedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<long?>("RegisteredByShopId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FullName")
                        .HasDatabaseName("IX_Customers_FullName");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("UQ_Customers_Phone")
                        .HasFilter("\"IsDeleted\" = false");

                    b.HasIndex("RegisteredByShopId")
                        .HasDatabaseName("IX_Customers_RegisteredByShopId");

                    b.ToTable("Customers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Customers_FullName_Length", "LENGTH(\"FullName\") >= 2");
                        });
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.FeeRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte>("CalculationType")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long?>("FlatAmount")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<long?>("MaxFee")
                        .HasColumnType("bigint");

                    b.Property<long?>("MinFee")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long?>("ModifiedByUserId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PercentValue")
                        .HasColumnType("numeric(5,4)");

                    b.Property<int>("WalletProviderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WalletProviderId", "EffectiveFromUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_FeeRules_Provider_EffectiveFrom");

                    b.ToTable("FeeRules", null, t =>
                        {
                            t.HasCheckConstraint("CK_FeeRule_Flat_Positive", "\"CalculationType\" <> 1 OR \"FlatAmount\" > 0");

                            t.HasCheckConstraint("CK_FeeRule_MinMax", "\"MinFee\" IS NULL OR \"MaxFee\" IS NULL OR \"MaxFee\" >= \"MinFee\"");

                            t.HasCheckConstraint("CK_FeeRule_Percent_Range", "\"CalculationType\" <> 2 OR (\"PercentValue\" > 0 AND \"PercentValue\" <= 100)");
                        });
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.FloatAdjustment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte>("AdjustmentTypeId")
                        .HasColumnType("smallint");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<long>("BalanceAfter")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Direction")
                        .HasColumnType("smallint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("WalletAccountId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AdjustmentTypeId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("WalletAccountId")
                        .HasDatabaseName("IX_FloatAdjustments_Account");

                    b.ToTable("FloatAdjustments", null, t =>
                        {
                            t.HasCheckConstraint("CK_FloatAdj_Amount_Positive", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.IdempotencyKey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ResponseJson")
                        .IsUnicode(true)
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_IdempotencyKeys_ExpiresAt");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("UQ_IdempotencyKeys_Key");

                    b.ToTable("IdempotencyKeys", (string)null);
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Permissions_Code");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "txn.create",
                            Description = "txn.create permission",
                            Module = "Txn"
                        },
                        new
                        {
                            Id = 2,
                            Code = "txn.cancel",
                            Description = "txn.cancel permission",
                            Module = "Txn"
                        },
                        new
                        {
                            Id = 3,
                            Code = "txn.reverse",
                            Description = "txn.reverse permission",
                            Module = "Txn"
                        },
                        new
                        {
                            Id = 4,
                            Code = "customer.manage",
                            Description = "customer.manage permission",
                            Module = "Customer"
                        },
                        new
                        {
                            Id = 5,
                            Code = "balance.adjust",
                            Description = "balance.adjust permission",
                            Module = "Balance"
                        },
                        new
                        {
                            Id = 6,
                            Code = "fee.manage",
                            Description = "fee.manage permission",
                            Module = "Fee"
                        },
                        new
                        {
                            Id = 7,
                            Code = "tenant.manage",
                            Description = "tenant.manage permission",
                            Module = "Platform"
                        },
                        new
                        {
                            Id = 8,
                            Code = "provider.manage",
                            Description = "provider.manage permission",
                            Module = "Admin"
                        },
                        new
                        {
                            Id = 9,
                            Code = "user.manage",
                            Description = "user.manage permission",
                            Module = "Admin"
                        },
                        new
                        {
                            Id = 10,
                            Code = "audit.view",
                            Description = "audit.view permission",
                            Module = "Admin"
                        },
                        new
                        {
                            Id = 11,
                            Code = "settings.manage",
                            Description = "settings.manage permission",
                            Module = "Admin"
                        },
                        new
                        {
                            Id = 12,
                            Code = "report.daily",
                            Description = "report.daily permission",
                            Module = "Report"
                        },
                        new
                        {
                            Id = 13,
                            Code = "report.profit",
                            Description = "report.profit permission",
                            Module = "Report"
                        });
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.PhysicalCashAccount", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<long>("CurrentCashBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<DateTime?>("LastReconciledAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("PhysicalCashAccounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_PhysicalCash_Nonneg", "\"CurrentCashBalance\" >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentCashBalance = 0L,
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UQ_RefreshTokens_TokenHash");

                    b.HasIndex("UserId", "RevokedAtUtc")
                        .HasDatabaseName("IX_RefreshTokens_User_Revoked");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsSystemRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Roles_Code");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SuperAdmin",
                            Description = "Platform owner",
                            IsSystemRole = true,
                            Name = "Super Admin"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Admin",
                            Description = "Shop administrator",
                            IsSystemRole = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Staff",
                            Description = "Shop staff",
                            IsSystemRole = true,
                            Name = "Staff"
                        });
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("IX_RolePermissions_PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 12
                        });
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.Shop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Shops_Code");

                    b.ToTable("Shops", (string)null);
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date");

                    b.Property<string>("CancellationReason")
                        .IsUnicode(true)
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long?>("CancelledByUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("CommissionAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomerNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CustomerPhoneSnapshot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("FeeAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<bool>("FeeOverridden")
                        .HasColumnType("boolean");

                    b.Property<int?>("FeeRuleId")
                        .HasColumnType("integer");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.Property<long?>("ReversalOfTxnId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReversalReason")
                        .IsUnicode(true)
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReversedAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long?>("ReversedByTxnId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReversedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ShopId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("TxnNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.Property<long>("WalletAccountId")
                        .HasColumnType("bigint");

                    b.Property<int>("WalletProviderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerPhoneSnapshot")
                        .HasDatabaseName("IX_Transactions_CustomerPhoneSnapshot");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UQ_Transactions_IdempotencyKey");

                    b.HasIndex("ReferenceNo")
                        .HasDatabaseName("IX_Transactions_ReferenceNo");

                    b.HasIndex("TxnNo")
                        .IsUnique()
                        .HasDatabaseName("UQ_Transactions_TxnNo");

                    b.HasIndex("WalletAccountId");

                    b.HasIndex("WalletProviderId");

                    b.HasIndex("CreatedByUserId", "BusinessDate")
                        .HasDatabaseName("IX_Transactions_CreatedBy_BusinessDate");

                    b.HasIndex("CustomerId", "BusinessDate")
                        .HasDatabaseName("IX_Transactions_CustomerId_BusinessDate");

                    b.HasIndex("ShopId", "BusinessDate")
                        .HasDatabaseName("IX_Transactions_ShopId_BusinessDate");

                    b.HasIndex("BusinessDate", "Type", "Status")
                        .HasDatabaseName("IX_Transactions_BusinessDate_Type_Status");

                    b.ToTable("Transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Txn_Amount_Positive", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_Txn_CommNonNeg", "\"CommissionAmount\" >= 0");

                            t.HasCheckConstraint("CK_Txn_FeeNonNeg", "\"FeeAmount\" >= 0");
                        });
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.TransactionCancellation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CancelledAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long>("CancelledByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("character varying(300)");

                    b.Property<long>("TransactionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_TransactionCancellations_Txn");

                    b.ToTable("TransactionCancellations", (string)null);
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.TransactionReversal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("MirrorTxnId")
                        .HasColumnType("bigint");

                    b.Property<long>("OriginalTxnId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("ReversedAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long>("ReversedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MirrorTxnId")
                        .IsUnique()
                        .HasDatabaseName("UQ_TransactionReversals_Mirror");

                    b.HasIndex("OriginalTxnId")
                        .IsUnique()
                        .HasDatabaseName("UQ_TransactionReversals_Original");

                    b.ToTable("TransactionReversals", null, t =>
                        {
                            t.HasCheckConstraint("CK_TransactionReversals_NotSelf", "\"OriginalTxnId\" <> \"MirrorTxnId\"");
                        });
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.TransactionStatusSeed", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("smallint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TransactionStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Code = "Pending",
                            Name = "Pending"
                        },
                        new
                        {
                            Id = (byte)2,
                            Code = "Completed",
                            Name = "Completed"
                        },
                        new
                        {
                            Id = (byte)3,
                            Code = "Cancelled",
                            Name = "Cancelled"
                        },
                        new
                        {
                            Id = (byte)4,
                            Code = "Reversed",
                            Name = "Reversed"
                        });
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.TransactionTypeSeed", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("smallint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(true)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TransactionTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Code = "CashIn",
                            Name = "Cash In"
                        },
                        new
                        {
                            Id = (byte)2,
                            Code = "CashOut",
                            Name = "Cash Out"
                        });
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<short>("FailedLoginCount")
                        .HasColumnType("smallint");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp(0) with time zone");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long?>("ModifiedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<long?>("ShopId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Phone")
                        .HasFilter("\"Phone\" IS NOT NULL AND \"IsDeleted\" = false");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_Users_RoleId");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("IX_Users_ShopId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_Username");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Username_Length", "LENGTH(\"Username\") >= 3");
                        });
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.WalletAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("CurrentFloatBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long?>("ModifiedByUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ShopId")
                        .HasColumnType("bigint");

                    b.Property<int>("WalletProviderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_WalletAccounts_AccountNumber")
                        .HasFilter("\"AccountNumber\" IS NOT NULL AND \"IsDeleted\" = false");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("IX_WalletAccounts_ShopId");

                    b.HasIndex("WalletProviderId")
                        .HasDatabaseName("IX_WalletAccounts_ProviderId");

                    b.ToTable("WalletAccounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_WalletAccounts_Float_Nonneg", "\"CurrentFloatBalance\" >= 0");
                        });
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.WalletLedgerEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<long>("BalanceAfter")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Direction")
                        .HasColumnType("smallint");

                    b.Property<long?>("FloatAdjustmentId")
                        .HasColumnType("bigint");

                    b.Property<byte>("SourceType")
                        .HasColumnType("smallint");

                    b.Property<long?>("TransactionId")
                        .HasColumnType("bigint");

                    b.Property<long>("WalletAccountId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("WalletAccountId", "CreatedAtUtc")
                        .HasDatabaseName("IX_WalletLedger_AccountId_CreatedAt");

                    b.ToTable("WalletLedgerEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_WalletLedger_Amount_Positive", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_WalletLedger_Source_Xor", "(\"SourceType\" = 1 AND \"TransactionId\" IS NOT NULL AND \"FloatAdjustmentId\" IS NULL) OR (\"SourceType\" = 2 AND \"FloatAdjustmentId\" IS NOT NULL AND \"TransactionId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.WalletProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_WalletProviders_Code");

                    b.ToTable("WalletProviders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "WAVE",
                            DisplayOrder = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Wave Money"
                        },
                        new
                        {
                            Id = 2,
                            Code = "KBZPAY",
                            DisplayOrder = 2,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "KBZPay"
                        });
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.CashAdjustment", b =>
                {
                    b.HasOne("MoneyRecord.Domain.Entities.AdjustmentType", null)
                        .WithMany()
                        .HasForeignKey("AdjustmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyRecord.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.CashLedgerEntry", b =>
                {
                    b.HasOne("MoneyRecord.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.CommissionEntry", b =>
                {
                    b.HasOne("MoneyRecord.Domain.Entities.CommissionSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyRecord.Domain.Entities.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Source");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.Customer", b =>
                {
                    b.HasOne("MoneyRecord.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyRecord.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.FeeRule", b =>
                {
                    b.HasOne("MoneyRecord.Domain.Entities.WalletProvider", "WalletProvider")
                        .WithMany()
                        .HasForeignKey("WalletProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WalletProvider");
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.FloatAdjustment", b =>
                {
                    b.HasOne("MoneyRecord.Domain.Entities.AdjustmentType", null)
                        .WithMany()
                        .HasForeignKey("AdjustmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyRecord.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyRecord.Domain.Entities.WalletAccount", null)
                        .WithMany()
                        .HasForeignKey("WalletAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("MoneyRecord.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("MoneyRecord.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyRecord.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("MoneyRecord.Domain.Entities.WalletAccount", "WalletAccount")
                        .WithMany()
                        .HasForeignKey("WalletAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyRecord.Domain.Entities.WalletProvider", "WalletProvider")
                        .WithMany()
                        .HasForeignKey("WalletProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WalletAccount");

                    b.Navigation("WalletProvider");
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.TransactionCancellation", b =>
                {
                    b.HasOne("MoneyRecord.Domain.Entities.Transaction", null)
                        .WithOne()
                        .HasForeignKey("MoneyRecord.Domain.Entities.TransactionCancellation", "TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.TransactionReversal", b =>
                {
                    b.HasOne("MoneyRecord.Domain.Entities.Transaction", null)
                        .WithOne()
                        .HasForeignKey("MoneyRecord.Domain.Entities.TransactionReversal", "MirrorTxnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyRecord.Domain.Entities.Transaction", null)
                        .WithOne()
                        .HasForeignKey("MoneyRecord.Domain.Entities.TransactionReversal", "OriginalTxnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.User", b =>
                {
                    b.HasOne("MoneyRecord.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyRecord.Domain.Entities.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Role");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.WalletAccount", b =>
                {
                    b.HasOne("MoneyRecord.Domain.Entities.WalletProvider", "WalletProvider")
                        .WithMany()
                        .HasForeignKey("WalletProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WalletProvider");
                });

            modelBuilder.Entity("MoneyRecord.Domain.Entities.WalletLedgerEntry", b =>
                {
                    b.HasOne("MoneyRecord.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoneyRecord.Domain.Entities.WalletAccount", null)
                        .WithMany()
                        .HasForeignKey("WalletAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
